version: '3.8'  # Specify the version of Docker Compose

services:
  web:
    image: missnayomie/myresume
    build:
      context: .  # Build from the Dockerfile in the current directory
    ports:
      - "8087:80"  # Map port 80 inside the container to port 8080 on the host
    volumes:
      - .:/usr/share/nginx/html  # Mount the current directory to the container
    restart: unless-stopped  # Automatically restart the container unless stopped
